// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzh6cxjk7J42UZAaPP_eRzJ03XWhe2jUA',
    appId: '1:75189513260:android:cf0dc3d8153f0c5968f589',
    messagingSenderId: '75189513260',
    projectId: 'aicampstudy',
    storageBucket: 'aicampstudy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzyapz86SmGN5cnUXeS7XO3w4dpnli1kE',
    appId: '1:75189513260:ios:50d16690cf1d723268f589',
    messagingSenderId: '75189513260',
    projectId: 'aicampstudy',
    storageBucket: 'aicampstudy.firebasestorage.app',
    iosBundleId: 'com.arvindgfx.aicamp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtF-eck2DgGpvONjHXcUc_IJnpOVGbjJw',
    appId: '1:75189513260:web:b847c9dce709df4a68f589',
    messagingSenderId: '75189513260',
    projectId: 'aicampstudy',
    authDomain: 'aicampstudy.firebaseapp.com',
    storageBucket: 'aicampstudy.firebasestorage.app',
    measurementId: 'G-MQHXX026RH',
  );

}